[package]
name = "day16-proboscidea-volcanium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "4.1.1"
itertools = "0.10.5"
nom = "7.1.2"
nom-supreme = "0.8.0"
petgraph = "0.6.2"
